///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class DelearListEmployeeDATA1 {
/*
{
  "Column1": 1
} 
*/

  String? Column1;

  DelearListEmployeeDATA1({
    this.Column1,
  });
  DelearListEmployeeDATA1.fromJson(Map<String, dynamic> json) {
    Column1 = json['Column1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Column1'] = Column1;
    return data;
  }
}

class DelearListEmployeeDATA {
/*
{
  "SHOP_ID": 41,
  "SHOP_NAME": "Aprozer Agri Services 125",
  "ADDRESS": "Satpur MIDC near satpur police station nashik",
  "CONTACT_NUMBER": "9868585888",
  "OWNER_NAME": "Ajinkya Aprozers",
  "SHOP_IMAGE": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/PHOTO7487737066.jpg",
  "STATE_ID": 27,
  "CITY_ID": 27,
  "TALUKA_ID": 27,
  "LATITUDE": "19.9810245",
  "LONGITUDE": "73.7574355",
  "STATUS": "Deactive",
  "REG_DATE": "2022-09-27T15:06:59.55",
  "USER_ID": 19,
  "DEALER_NAME": "Ajinkya Aprozers",
  "VILLAGE": "nashik",
  "PINCODE": "422047",
  "EMAIL": null,
  "FETLIZER_LIC_NO": "ffh57577575",
  "PESTISIDE_LIC_NO": "p58575757f",
  "SEED_LIC_NO": "8586585",
  "VALID_UPTO": "2026-09-30T00:00:00",
  "PAN_NUMBER": "gjgjgj55575758",
  "GST_NUMBER": "gdhf75577575",
  "SHOP_OWNER_PHOTO": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/OWNERPHOTO9078757965.jpg",
  "STATE_NAME": "MAHARASHTRA",
  "CITY_NAME": "Gurdaspur",
  "TALUKA_NAME": "Leh"
} 
*/

  String? SHOP_ID;
  String? SHOP_NAME;
  String? ADDRESS;
  String? CONTACT_NUMBER;
  String? OWNER_NAME;
  String? SHOP_IMAGE;
  String? STATE_ID;
  String? CITY_ID;
  String? TALUKA_ID;
  String? LATITUDE;
  String? LONGITUDE;
  String? STATUS;
  String? REG_DATE;
  String? USER_ID;
  String? DEALER_NAME;
  String? VILLAGE;
  String? PINCODE;
  String? EMAIL;
  String? FETLIZER_LIC_NO;
  String? PESTISIDE_LIC_NO;
  String? SEED_LIC_NO;
  String? VALID_UPTO;
  String? PAN_NUMBER;
  String? GST_NUMBER;
  String? SHOP_OWNER_PHOTO;
  String? STATE_NAME;
  String? CITY_NAME;
  String? TALUKA_NAME;

  DelearListEmployeeDATA({
    this.SHOP_ID,
    this.SHOP_NAME,
    this.ADDRESS,
    this.CONTACT_NUMBER,
    this.OWNER_NAME,
    this.SHOP_IMAGE,
    this.STATE_ID,
    this.CITY_ID,
    this.TALUKA_ID,
    this.LATITUDE,
    this.LONGITUDE,
    this.STATUS,
    this.REG_DATE,
    this.USER_ID,
    this.DEALER_NAME,
    this.VILLAGE,
    this.PINCODE,
    this.EMAIL,
    this.FETLIZER_LIC_NO,
    this.PESTISIDE_LIC_NO,
    this.SEED_LIC_NO,
    this.VALID_UPTO,
    this.PAN_NUMBER,
    this.GST_NUMBER,
    this.SHOP_OWNER_PHOTO,
    this.STATE_NAME,
    this.CITY_NAME,
    this.TALUKA_NAME,
  });
  DelearListEmployeeDATA.fromJson(Map<String, dynamic> json) {
    SHOP_ID = json['SHOP_ID']?.toString();
    SHOP_NAME = json['SHOP_NAME']?.toString();
    ADDRESS = json['ADDRESS']?.toString();
    CONTACT_NUMBER = json['CONTACT_NUMBER']?.toString();
    OWNER_NAME = json['OWNER_NAME']?.toString();
    SHOP_IMAGE = json['SHOP_IMAGE']?.toString();
    STATE_ID = json['STATE_ID']?.toString();
    CITY_ID = json['CITY_ID']?.toString();
    TALUKA_ID = json['TALUKA_ID']?.toString();
    LATITUDE = json['LATITUDE']?.toString();
    LONGITUDE = json['LONGITUDE']?.toString();
    STATUS = json['STATUS']?.toString();
    REG_DATE = json['REG_DATE']?.toString();
    USER_ID = json['USER_ID']?.toString();
    DEALER_NAME = json['DEALER_NAME']?.toString();
    VILLAGE = json['VILLAGE']?.toString();
    PINCODE = json['PINCODE']?.toString();
    EMAIL = json['EMAIL']?.toString();
    FETLIZER_LIC_NO = json['FETLIZER_LIC_NO']?.toString();
    PESTISIDE_LIC_NO = json['PESTISIDE_LIC_NO']?.toString();
    SEED_LIC_NO = json['SEED_LIC_NO']?.toString();
    VALID_UPTO = json['VALID_UPTO']?.toString();
    PAN_NUMBER = json['PAN_NUMBER']?.toString();
    GST_NUMBER = json['GST_NUMBER']?.toString();
    SHOP_OWNER_PHOTO = json['SHOP_OWNER_PHOTO']?.toString();
    STATE_NAME = json['STATE_NAME']?.toString();
    CITY_NAME = json['CITY_NAME']?.toString();
    TALUKA_NAME = json['TALUKA_NAME']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['SHOP_ID'] = SHOP_ID;
    data['SHOP_NAME'] = SHOP_NAME;
    data['ADDRESS'] = ADDRESS;
    data['CONTACT_NUMBER'] = CONTACT_NUMBER;
    data['OWNER_NAME'] = OWNER_NAME;
    data['SHOP_IMAGE'] = SHOP_IMAGE;
    data['STATE_ID'] = STATE_ID;
    data['CITY_ID'] = CITY_ID;
    data['TALUKA_ID'] = TALUKA_ID;
    data['LATITUDE'] = LATITUDE;
    data['LONGITUDE'] = LONGITUDE;
    data['STATUS'] = STATUS;
    data['REG_DATE'] = REG_DATE;
    data['USER_ID'] = USER_ID;
    data['DEALER_NAME'] = DEALER_NAME;
    data['VILLAGE'] = VILLAGE;
    data['PINCODE'] = PINCODE;
    data['EMAIL'] = EMAIL;
    data['FETLIZER_LIC_NO'] = FETLIZER_LIC_NO;
    data['PESTISIDE_LIC_NO'] = PESTISIDE_LIC_NO;
    data['SEED_LIC_NO'] = SEED_LIC_NO;
    data['VALID_UPTO'] = VALID_UPTO;
    data['PAN_NUMBER'] = PAN_NUMBER;
    data['GST_NUMBER'] = GST_NUMBER;
    data['SHOP_OWNER_PHOTO'] = SHOP_OWNER_PHOTO;
    data['STATE_NAME'] = STATE_NAME;
    data['CITY_NAME'] = CITY_NAME;
    data['TALUKA_NAME'] = TALUKA_NAME;
    return data;
  }
}

class DelearListEmployee {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Shop List",
  "Otp": null,
  "Static_Otp": null,
  "DATA": [
    {
      "SHOP_ID": 41,
      "SHOP_NAME": "Aprozer Agri Services 125",
      "ADDRESS": "Satpur MIDC near satpur police station nashik",
      "CONTACT_NUMBER": "9868585888",
      "OWNER_NAME": "Ajinkya Aprozers",
      "SHOP_IMAGE": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/PHOTO7487737066.jpg",
      "STATE_ID": 27,
      "CITY_ID": 27,
      "TALUKA_ID": 27,
      "LATITUDE": "19.9810245",
      "LONGITUDE": "73.7574355",
      "STATUS": "Deactive",
      "REG_DATE": "2022-09-27T15:06:59.55",
      "USER_ID": 19,
      "DEALER_NAME": "Ajinkya Aprozers",
      "VILLAGE": "nashik",
      "PINCODE": "422047",
      "EMAIL": null,
      "FETLIZER_LIC_NO": "ffh57577575",
      "PESTISIDE_LIC_NO": "p58575757f",
      "SEED_LIC_NO": "8586585",
      "VALID_UPTO": "2026-09-30T00:00:00",
      "PAN_NUMBER": "gjgjgj55575758",
      "GST_NUMBER": "gdhf75577575",
      "SHOP_OWNER_PHOTO": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/OWNERPHOTO9078757965.jpg",
      "STATE_NAME": "MAHARASHTRA",
      "CITY_NAME": "Gurdaspur",
      "TALUKA_NAME": "Leh"
    }
  ],
  "DATA1": [
    {
      "Column1": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? Otp;
  String? Static_Otp;
  List<DelearListEmployeeDATA?>? DATA;
  List<DelearListEmployeeDATA1?>? DATA1;

  DelearListEmployee({
    this.ResponseCode,
    this.ResponseMessage,
    this.Otp,
    this.Static_Otp,
    this.DATA,
    this.DATA1,
  });
  DelearListEmployee.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    Otp = json['Otp']?.toString();
    Static_Otp = json['Static_Otp']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <DelearListEmployeeDATA>[];
  v.forEach((v) {
  arr0.add(DelearListEmployeeDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <DelearListEmployeeDATA1>[];
  v.forEach((v) {
  arr0.add(DelearListEmployeeDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['Otp'] = Otp;
    data['Static_Otp'] = Static_Otp;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    return data;
  }
}
