///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class AskQuestionModelDATA1 {
/*
{
  "Column1": 1
} 
*/

  String? Column1;

  AskQuestionModelDATA1({
    this.Column1,
  });
  AskQuestionModelDATA1.fromJson(Map<String, dynamic> json) {
    Column1 = json['Column1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Column1'] = Column1;
    return data;
  }
}

class AskQuestionModelDATA {
/*
{
  "Row": 1,
  "NEWQUETION_ID": 55960,
  "NEWQUETION": "ggg",
  "DESCRIPTION": "TEXT",
  "REG_DATE": "30/01/2024",
  "STATUS": "Unsolved",
  "QUESTIO_TIME": "2024-01-30T13:48:26.19",
  "IMAGE_URL": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/PHOTO8978669086.jpg",
  "ADMIN_IMG": null,
  "SOLVED_DATETIME": null,
  "VIDEO_URL": null,
  "LIKE_STATUS": null,
  "LIKE_DATE": null,
  "QUE_ANSWER": null,
  "FAQC_NAME": "मिलिबग      ಮಿಲಿಬಗ",
  "AUDIO_URL": null
} 
*/

  String? Row;
  String? NEWQUETION_ID;
  String? NEWQUETION;
  String? DESCRIPTION;
  String? REG_DATE;
  String? STATUS;
  String? QUESTIO_TIME;
  String? IMAGE_URL;
  String? ADMIN_IMG;
  String? SOLVED_DATETIME;
  String? VIDEO_URL;
  String? LIKE_STATUS;
  String? LIKE_DATE;
  String? QUE_ANSWER;
  String? FAQC_NAME;
  String? AUDIO_URL;

  AskQuestionModelDATA({
    this.Row,
    this.NEWQUETION_ID,
    this.NEWQUETION,
    this.DESCRIPTION,
    this.REG_DATE,
    this.STATUS,
    this.QUESTIO_TIME,
    this.IMAGE_URL,
    this.ADMIN_IMG,
    this.SOLVED_DATETIME,
    this.VIDEO_URL,
    this.LIKE_STATUS,
    this.LIKE_DATE,
    this.QUE_ANSWER,
    this.FAQC_NAME,
    this.AUDIO_URL,
  });
  AskQuestionModelDATA.fromJson(Map<String, dynamic> json) {
    Row = json['Row']?.toString();
    NEWQUETION_ID = json['NEWQUETION_ID']?.toString();
    NEWQUETION = json['NEWQUETION']?.toString();
    DESCRIPTION = json['DESCRIPTION']?.toString();
    REG_DATE = json['REG_DATE']?.toString();
    STATUS = json['STATUS']?.toString();
    QUESTIO_TIME = json['QUESTIO_TIME']?.toString();
    IMAGE_URL = json['IMAGE_URL']?.toString();
    ADMIN_IMG = json['ADMIN_IMG']?.toString();
    SOLVED_DATETIME = json['SOLVED_DATETIME']?.toString();
    VIDEO_URL = json['VIDEO_URL']?.toString();
    LIKE_STATUS = json['LIKE_STATUS']?.toString();
    LIKE_DATE = json['LIKE_DATE']?.toString();
    QUE_ANSWER = json['QUE_ANSWER']?.toString();
    FAQC_NAME = json['FAQC_NAME']?.toString();
    AUDIO_URL = json['AUDIO_URL']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Row'] = Row;
    data['NEWQUETION_ID'] = NEWQUETION_ID;
    data['NEWQUETION'] = NEWQUETION;
    data['DESCRIPTION'] = DESCRIPTION;
    data['REG_DATE'] = REG_DATE;
    data['STATUS'] = STATUS;
    data['QUESTIO_TIME'] = QUESTIO_TIME;
    data['IMAGE_URL'] = IMAGE_URL;
    data['ADMIN_IMG'] = ADMIN_IMG;
    data['SOLVED_DATETIME'] = SOLVED_DATETIME;
    data['VIDEO_URL'] = VIDEO_URL;
    data['LIKE_STATUS'] = LIKE_STATUS;
    data['LIKE_DATE'] = LIKE_DATE;
    data['QUE_ANSWER'] = QUE_ANSWER;
    data['FAQC_NAME'] = FAQC_NAME;
    data['AUDIO_URL'] = AUDIO_URL;
    return data;
  }
}

class AskQuestionModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Farmer Question List",
  "Otp": null,
  "Static_Otp": null,
  "DATA": [
    {
      "Row": 1,
      "NEWQUETION_ID": 55960,
      "NEWQUETION": "ggg",
      "DESCRIPTION": "TEXT",
      "REG_DATE": "30/01/2024",
      "STATUS": "Unsolved",
      "QUESTIO_TIME": "2024-01-30T13:48:26.19",
      "IMAGE_URL": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/PHOTO8978669086.jpg",
      "ADMIN_IMG": null,
      "SOLVED_DATETIME": null,
      "VIDEO_URL": null,
      "LIKE_STATUS": null,
      "LIKE_DATE": null,
      "QUE_ANSWER": null,
      "FAQC_NAME": "मिलिबग      ಮಿಲಿಬಗ",
      "AUDIO_URL": null
    }
  ],
  "DATA1": [
    {
      "Column1": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? Otp;
  String? Static_Otp;
  List<AskQuestionModelDATA?>? DATA;
  List<AskQuestionModelDATA1?>? DATA1;

  AskQuestionModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.Otp,
    this.Static_Otp,
    this.DATA,
    this.DATA1,
  });
  AskQuestionModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    Otp = json['Otp']?.toString();
    Static_Otp = json['Static_Otp']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <AskQuestionModelDATA>[];
  v.forEach((v) {
  arr0.add(AskQuestionModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <AskQuestionModelDATA1>[];
  v.forEach((v) {
  arr0.add(AskQuestionModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['Otp'] = Otp;
    data['Static_Otp'] = Static_Otp;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    return data;
  }
}
