///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class SheduleListModelDATA1 {
/*
{
  "Row": 1,
  "SCHEDULE_ID": 143681,
  "SCHEDULE_TITLE": "गोडीबहार छाटणी दिवस ",
  "DESCRIPTION": "आपल्या प्लॉट चे निरीक्षण करणे व  काही समस्या असल्यास विचारा तुम्हीं सांगतो आम्हीं या विंडो मधून प्रश्न पाठवा.",
  "SCHEDULE_DAY": 119,
  "SCHEDULE_IMAGE": "NULL",
  "PLOT_IMPORT_EXPORT": "NULL",
  "SCHEDULE_VIDEO": null,
  "SCHEDULE_TYPE": "Spray",
  "DISEASE_PEST": "",
  "FUNCTIONAL_COMPONANT": "",
  "PHI": "",
  "STATUS": "Active",
  "REG_DATE": "2022-08-02T00:00:00",
  "SCHEDULE_DATE": "07/11/2022",
  "IS_COMPLETED": "No"
} 
*/

  String? Row;
  String? SCHEDULE_ID;
  String? SCHEDULE_TITLE;
  String? DESCRIPTION;
  String? SCHEDULE_DAY;
  String? SCHEDULE_IMAGE;
  String? PLOT_IMPORT_EXPORT;
  String? SCHEDULE_VIDEO;
  String? SCHEDULE_TYPE;
  String? DISEASE_PEST;
  String? FUNCTIONAL_COMPONANT;
  String? PHI;
  String? STATUS;
  String? REG_DATE;
  String? SCHEDULE_DATE;
  String? IS_COMPLETED;

  SheduleListModelDATA1({
    this.Row,
    this.SCHEDULE_ID,
    this.SCHEDULE_TITLE,
    this.DESCRIPTION,
    this.SCHEDULE_DAY,
    this.SCHEDULE_IMAGE,
    this.PLOT_IMPORT_EXPORT,
    this.SCHEDULE_VIDEO,
    this.SCHEDULE_TYPE,
    this.DISEASE_PEST,
    this.FUNCTIONAL_COMPONANT,
    this.PHI,
    this.STATUS,
    this.REG_DATE,
    this.SCHEDULE_DATE,
    this.IS_COMPLETED,
  });
  SheduleListModelDATA1.fromJson(Map<String, dynamic> json) {
    Row = json['Row']?.toString();
    SCHEDULE_ID = json['SCHEDULE_ID']?.toString();
    SCHEDULE_TITLE = json['SCHEDULE_TITLE']?.toString();
    DESCRIPTION = json['DESCRIPTION']?.toString();
    SCHEDULE_DAY = json['SCHEDULE_DAY']?.toString();
    SCHEDULE_IMAGE = json['SCHEDULE_IMAGE']?.toString();
    PLOT_IMPORT_EXPORT = json['PLOT_IMPORT_EXPORT']?.toString();
    SCHEDULE_VIDEO = json['SCHEDULE_VIDEO']?.toString();
    SCHEDULE_TYPE = json['SCHEDULE_TYPE']?.toString();
    DISEASE_PEST = json['DISEASE_PEST']?.toString();
    FUNCTIONAL_COMPONANT = json['FUNCTIONAL_COMPONANT']?.toString();
    PHI = json['PHI']?.toString();
    STATUS = json['STATUS']?.toString();
    REG_DATE = json['REG_DATE']?.toString();
    SCHEDULE_DATE = json['SCHEDULE_DATE']?.toString();
    IS_COMPLETED = json['IS_COMPLETED']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Row'] = Row;
    data['SCHEDULE_ID'] = SCHEDULE_ID;
    data['SCHEDULE_TITLE'] = SCHEDULE_TITLE;
    data['DESCRIPTION'] = DESCRIPTION;
    data['SCHEDULE_DAY'] = SCHEDULE_DAY;
    data['SCHEDULE_IMAGE'] = SCHEDULE_IMAGE;
    data['PLOT_IMPORT_EXPORT'] = PLOT_IMPORT_EXPORT;
    data['SCHEDULE_VIDEO'] = SCHEDULE_VIDEO;
    data['SCHEDULE_TYPE'] = SCHEDULE_TYPE;
    data['DISEASE_PEST'] = DISEASE_PEST;
    data['FUNCTIONAL_COMPONANT'] = FUNCTIONAL_COMPONANT;
    data['PHI'] = PHI;
    data['STATUS'] = STATUS;
    data['REG_DATE'] = REG_DATE;
    data['SCHEDULE_DATE'] = SCHEDULE_DATE;
    data['IS_COMPLETED'] = IS_COMPLETED;
    return data;
  }
}

class SheduleListModelDATA {
/*
{
  "Row": 1,
  "SCHEDULE_ID": 1165969,
  "SCHEDULE_TITLE": "गोडीबहार छाटणी फवारणी नियोजन\t",
  "DESCRIPTION": "आपल्या प्लॉट चे निरीक्षण करणे व  काही समस्या असल्यास विचारा तुम्हीं सांगतो आम्हीं या विंडो मधून प्रश्न पाठवा.",
  "SCHEDULE_DAY": 119,
  "SCHEDULE_IMAGE": "",
  "PLOT_IMPORT_EXPORT": "Local",
  "SCHEDULE_VIDEO": "",
  "SCHEDULE_TYPE": "Spray",
  "DISEASE_PEST": "",
  "FUNCTIONAL_COMPONANT": "",
  "PHI": "",
  "STATUS": "Active",
  "REG_DATE": "2023-10-07T00:00:00",
  "SCHEDULE_DATE": "07/11/2022",
  "IS_COMPLETED": "No"
} 
*/

  String? Row;
  String? SCHEDULE_ID;
  String? SCHEDULE_TITLE;
  String? DESCRIPTION;
  int? SCHEDULE_DAY;
  String? SCHEDULE_IMAGE;
  String? PLOT_IMPORT_EXPORT;
  String? SCHEDULE_VIDEO;
  String? SCHEDULE_TYPE;
  String? DISEASE_PEST;
  String? FUNCTIONAL_COMPONANT;
  String? PHI;
  String? STATUS;
  String? REG_DATE;
  String? SCHEDULE_DATE;
  String? IS_COMPLETED;

  SheduleListModelDATA({
    this.Row,
    this.SCHEDULE_ID,
    this.SCHEDULE_TITLE,
    this.DESCRIPTION,
    this.SCHEDULE_DAY,
    this.SCHEDULE_IMAGE,
    this.PLOT_IMPORT_EXPORT,
    this.SCHEDULE_VIDEO,
    this.SCHEDULE_TYPE,
    this.DISEASE_PEST,
    this.FUNCTIONAL_COMPONANT,
    this.PHI,
    this.STATUS,
    this.REG_DATE,
    this.SCHEDULE_DATE,
    this.IS_COMPLETED,
  });
  SheduleListModelDATA.fromJson(Map<String, dynamic> json) {
    Row = json['Row']?.toString();
    SCHEDULE_ID = json['SCHEDULE_ID']?.toString();
    SCHEDULE_TITLE = json['SCHEDULE_TITLE']?.toString();
    DESCRIPTION = json['DESCRIPTION']?.toString();
    SCHEDULE_DAY = json['SCHEDULE_DAY'];
    SCHEDULE_IMAGE = json['SCHEDULE_IMAGE']?.toString();
    PLOT_IMPORT_EXPORT = json['PLOT_IMPORT_EXPORT']?.toString();
    SCHEDULE_VIDEO = json['SCHEDULE_VIDEO']?.toString();
    SCHEDULE_TYPE = json['SCHEDULE_TYPE']?.toString();
    DISEASE_PEST = json['DISEASE_PEST']?.toString();
    FUNCTIONAL_COMPONANT = json['FUNCTIONAL_COMPONANT']?.toString();
    PHI = json['PHI']?.toString();
    STATUS = json['STATUS']?.toString();
    REG_DATE = json['REG_DATE']?.toString();
    SCHEDULE_DATE = json['SCHEDULE_DATE']?.toString();
    IS_COMPLETED = json['IS_COMPLETED']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Row'] = Row;
    data['SCHEDULE_ID'] = SCHEDULE_ID;
    data['SCHEDULE_TITLE'] = SCHEDULE_TITLE;
    data['DESCRIPTION'] = DESCRIPTION;
    data['SCHEDULE_DAY'] = SCHEDULE_DAY;
    data['SCHEDULE_IMAGE'] = SCHEDULE_IMAGE;
    data['PLOT_IMPORT_EXPORT'] = PLOT_IMPORT_EXPORT;
    data['SCHEDULE_VIDEO'] = SCHEDULE_VIDEO;
    data['SCHEDULE_TYPE'] = SCHEDULE_TYPE;
    data['DISEASE_PEST'] = DISEASE_PEST;
    data['FUNCTIONAL_COMPONANT'] = FUNCTIONAL_COMPONANT;
    data['PHI'] = PHI;
    data['STATUS'] = STATUS;
    data['REG_DATE'] = REG_DATE;
    data['SCHEDULE_DATE'] = SCHEDULE_DATE;
    data['IS_COMPLETED'] = IS_COMPLETED;
    return data;
  }
}

class SheduleListModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Post Schedule List",
  "Otp": null,
  "Static_Otp": null,
  "DATA": [
    {
      "Row": 1,
      "SCHEDULE_ID": 1165969,
      "SCHEDULE_TITLE": "गोडीबहार छाटणी फवारणी नियोजन\t",
      "DESCRIPTION": "आपल्या प्लॉट चे निरीक्षण करणे व  काही समस्या असल्यास विचारा तुम्हीं सांगतो आम्हीं या विंडो मधून प्रश्न पाठवा.",
      "SCHEDULE_DAY": 119,
      "SCHEDULE_IMAGE": "",
      "PLOT_IMPORT_EXPORT": "Local",
      "SCHEDULE_VIDEO": "",
      "SCHEDULE_TYPE": "Spray",
      "DISEASE_PEST": "",
      "FUNCTIONAL_COMPONANT": "",
      "PHI": "",
      "STATUS": "Active",
      "REG_DATE": "2023-10-07T00:00:00",
      "SCHEDULE_DATE": "07/11/2022",
      "IS_COMPLETED": "No"
    }
  ],
  "DATA1": [
    {
      "Row": 1,
      "SCHEDULE_ID": 143681,
      "SCHEDULE_TITLE": "गोडीबहार छाटणी दिवस ",
      "DESCRIPTION": "आपल्या प्लॉट चे निरीक्षण करणे व  काही समस्या असल्यास विचारा तुम्हीं सांगतो आम्हीं या विंडो मधून प्रश्न पाठवा.",
      "SCHEDULE_DAY": 119,
      "SCHEDULE_IMAGE": "NULL",
      "PLOT_IMPORT_EXPORT": "NULL",
      "SCHEDULE_VIDEO": null,
      "SCHEDULE_TYPE": "Spray",
      "DISEASE_PEST": "",
      "FUNCTIONAL_COMPONANT": "",
      "PHI": "",
      "STATUS": "Active",
      "REG_DATE": "2022-08-02T00:00:00",
      "SCHEDULE_DATE": "07/11/2022",
      "IS_COMPLETED": "No"
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? Otp;
  String? Static_Otp;
  List<SheduleListModelDATA?>? DATA;
  List<SheduleListModelDATA1?>? DATA1;

  SheduleListModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.Otp,
    this.Static_Otp,
    this.DATA,
    this.DATA1,
  });
  SheduleListModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    Otp = json['Otp']?.toString();
    Static_Otp = json['Static_Otp']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <SheduleListModelDATA>[];
  v.forEach((v) {
  arr0.add(SheduleListModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <SheduleListModelDATA1>[];
  v.forEach((v) {
  arr0.add(SheduleListModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['Otp'] = Otp;
    data['Static_Otp'] = Static_Otp;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    return data;
  }
}
