///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class SubScriptionListModelDATA1 {
/*
{
  "TABLE1": 1
} 
*/

  String? TABLE1;

  SubScriptionListModelDATA1({
    this.TABLE1,
  });
  SubScriptionListModelDATA1.fromJson(Map<String, dynamic> json) {
    TABLE1 = json['TABLE1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TABLE1'] = TABLE1;
    return data;
  }
}

class SubScriptionListModelDATA {
/*
{
  "PACKAGE_ID": 52,
  "PACKAGE_NAME": "मेथी मास्टर पॅकेज",
  "PACKAGE_DESCRIPTION": "मेथी मास्टर पॅकेज",
  "PACKAGE_IMG": null,
  "PACKAGE_DAY": 60,
  "AMOUNT": 199,
  "CROP_IMAGE": "http://cmadmin.cropmaster.in///Images/Crop66797375737204352023.jpg"
} 
*/

  String? PACKAGE_ID;
  String? PACKAGE_NAME;
  String? PACKAGE_DESCRIPTION;
  String? PACKAGE_IMG;
  String? PACKAGE_DAY;
  String? AMOUNT;
  String? CROP_IMAGE;

  SubScriptionListModelDATA({
    this.PACKAGE_ID,
    this.PACKAGE_NAME,
    this.PACKAGE_DESCRIPTION,
    this.PACKAGE_IMG,
    this.PACKAGE_DAY,
    this.AMOUNT,
    this.CROP_IMAGE,
  });
  SubScriptionListModelDATA.fromJson(Map<String, dynamic> json) {
    PACKAGE_ID = json['PACKAGE_ID']?.toString();
    PACKAGE_NAME = json['PACKAGE_NAME']?.toString();
    PACKAGE_DESCRIPTION = json['PACKAGE_DESCRIPTION']?.toString();
    PACKAGE_IMG = json['PACKAGE_IMG']?.toString();
    PACKAGE_DAY = json['PACKAGE_DAY']?.toString();
    AMOUNT = json['AMOUNT']?.toString();
    CROP_IMAGE = json['CROP_IMAGE']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['PACKAGE_ID'] = PACKAGE_ID;
    data['PACKAGE_NAME'] = PACKAGE_NAME;
    data['PACKAGE_DESCRIPTION'] = PACKAGE_DESCRIPTION;
    data['PACKAGE_IMG'] = PACKAGE_IMG;
    data['PACKAGE_DAY'] = PACKAGE_DAY;
    data['AMOUNT'] = AMOUNT;
    data['CROP_IMAGE'] = CROP_IMAGE;
    return data;
  }
}

class SubScriptionListModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Get_PackageMaster List",
  "Otp": null,
  "Static_Otp": null,
  "DATA": [
    {
      "PACKAGE_ID": 52,
      "PACKAGE_NAME": "मेथी मास्टर पॅकेज",
      "PACKAGE_DESCRIPTION": "मेथी मास्टर पॅकेज",
      "PACKAGE_IMG": null,
      "PACKAGE_DAY": 60,
      "AMOUNT": 199,
      "CROP_IMAGE": "http://cmadmin.cropmaster.in///Images/Crop66797375737204352023.jpg"
    }
  ],
  "DATA1": [
    {
      "TABLE1": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? Otp;
  String? Static_Otp;
  List<SubScriptionListModelDATA?>? DATA;
  List<SubScriptionListModelDATA1?>? DATA1;

  SubScriptionListModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.Otp,
    this.Static_Otp,
    this.DATA,
    this.DATA1,
  });
  SubScriptionListModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    Otp = json['Otp']?.toString();
    Static_Otp = json['Static_Otp']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <SubScriptionListModelDATA>[];
  v.forEach((v) {
  arr0.add(SubScriptionListModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <SubScriptionListModelDATA1>[];
  v.forEach((v) {
  arr0.add(SubScriptionListModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['Otp'] = Otp;
    data['Static_Otp'] = Static_Otp;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    return data;
  }
}
