///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class PostModelDATA1 {
/*
{
  "Column1": 1
} 
*/

  String? Column1;

  PostModelDATA1({
    this.Column1,
  });
  PostModelDATA1.fromJson(Map<String, dynamic> json) {
    Column1 = json['Column1']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Column1'] = Column1;
    return data;
  }
}

class PostModelDATA {
/*
{
  "Row": 1,
  "POST_ID": 587,
  "FULL_NAME": "jnaneshwar",
  "MOBILE_NUMBER": "8151904373",
  "PROFILE_PHOTO": "",
  "POST_IMAGE": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/PHOTO8290848282.jpg",
  "POST_DESCRIPTION": "Iska kay karne chay",
  "POST_TITLE": null,
  "REG_DATE": "04/01/2024",
  "CROP_NAME": "द्राक्षे",
  "LIKE_COUNT": 0,
  "COMMENT_COUNT": 0,
  "IS_LIKE": "No",
  "CROP_ID": 1
} 
*/

  String? Row;
  String? POST_ID;
  String? FULL_NAME;
  String? MOBILE_NUMBER;
  String? PROFILE_PHOTO;
  String? POST_IMAGE;
  String? POST_DESCRIPTION;
  String? POST_TITLE;
  String? REG_DATE;
  String? CROP_NAME;
  String? LIKE_COUNT;
  String? COMMENT_COUNT;
  String? IS_LIKE;
  String? CROP_ID;

  PostModelDATA({
    this.Row,
    this.POST_ID,
    this.FULL_NAME,
    this.MOBILE_NUMBER,
    this.PROFILE_PHOTO,
    this.POST_IMAGE,
    this.POST_DESCRIPTION,
    this.POST_TITLE,
    this.REG_DATE,
    this.CROP_NAME,
    this.LIKE_COUNT,
    this.COMMENT_COUNT,
    this.IS_LIKE,
    this.CROP_ID,
  });
  PostModelDATA.fromJson(Map<String, dynamic> json) {
    Row = json['Row']?.toString();
    POST_ID = json['POST_ID']?.toString();
    FULL_NAME = json['FULL_NAME']?.toString();
    MOBILE_NUMBER = json['MOBILE_NUMBER']?.toString();
    PROFILE_PHOTO = json['PROFILE_PHOTO']?.toString();
    POST_IMAGE = json['POST_IMAGE']?.toString();
    POST_DESCRIPTION = json['POST_DESCRIPTION']?.toString();
    POST_TITLE = json['POST_TITLE']?.toString();
    REG_DATE = json['REG_DATE']?.toString();
    CROP_NAME = json['CROP_NAME']?.toString();
    LIKE_COUNT = json['LIKE_COUNT']?.toString();
    COMMENT_COUNT = json['COMMENT_COUNT']?.toString();
    IS_LIKE = json['IS_LIKE']?.toString();
    CROP_ID = json['CROP_ID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Row'] = Row;
    data['POST_ID'] = POST_ID;
    data['FULL_NAME'] = FULL_NAME;
    data['MOBILE_NUMBER'] = MOBILE_NUMBER;
    data['PROFILE_PHOTO'] = PROFILE_PHOTO;
    data['POST_IMAGE'] = POST_IMAGE;
    data['POST_DESCRIPTION'] = POST_DESCRIPTION;
    data['POST_TITLE'] = POST_TITLE;
    data['REG_DATE'] = REG_DATE;
    data['CROP_NAME'] = CROP_NAME;
    data['LIKE_COUNT'] = LIKE_COUNT;
    data['COMMENT_COUNT'] = COMMENT_COUNT;
    data['IS_LIKE'] = IS_LIKE;
    data['CROP_ID'] = CROP_ID;
    return data;
  }
}

class PostModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Post List",
  "Otp": null,
  "Static_Otp": null,
  "DATA": [
    {
      "Row": 1,
      "POST_ID": 587,
      "FULL_NAME": "jnaneshwar",
      "MOBILE_NUMBER": "8151904373",
      "PROFILE_PHOTO": "",
      "POST_IMAGE": "http://newgrapemastersnskapi.cropmaster.in/ImagesUploaded/PHOTO8290848282.jpg",
      "POST_DESCRIPTION": "Iska kay karne chay",
      "POST_TITLE": null,
      "REG_DATE": "04/01/2024",
      "CROP_NAME": "द्राक्षे",
      "LIKE_COUNT": 0,
      "COMMENT_COUNT": 0,
      "IS_LIKE": "No",
      "CROP_ID": 1
    }
  ],
  "DATA1": [
    {
      "Column1": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? Otp;
  String? Static_Otp;
  List<PostModelDATA?>? DATA;
  List<PostModelDATA1?>? DATA1;

  PostModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.Otp,
    this.Static_Otp,
    this.DATA,
    this.DATA1,
  });
  PostModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    Otp = json['Otp']?.toString();
    Static_Otp = json['Static_Otp']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <PostModelDATA>[];
  v.forEach((v) {
  arr0.add(PostModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <PostModelDATA1>[];
  v.forEach((v) {
  arr0.add(PostModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['Otp'] = Otp;
    data['Static_Otp'] = Static_Otp;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    return data;
  }
}
