///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
const String jsonKeyNearByShopModelResponseCode = 'ResponseCode';
const String jsonKeyNearByShopModelResponseMessage = 'ResponseMessage';
const String jsonKeyNearByShopModelOtp = 'Otp';
const String jsonKeyNearByShopModelStatic_Otp = 'Static_Otp';
const String jsonKeyNearByShopModelDATA = 'DATA';
const String jsonKeyNearByShopModelDATA1 = 'DATA1';
const String jsonKeyNearByShopModelDATA1Column1 = 'Column1';
class NearByShopModelDATA1 {
/*
{
  "Column1": 1
} 
*/

  int? Column1;

  NearByShopModelDATA1({
    this.Column1,
  });
  NearByShopModelDATA1.fromJson(Map<String, dynamic> json) {
    Column1 = json[jsonKeyNearByShopModelDATA1Column1]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[jsonKeyNearByShopModelDATA1Column1] = Column1;
    return data;
  }
}

const String jsonKeyNearByShopModelDATARow = 'Row';
const String jsonKeyNearByShopModelDATASHOP_ID = 'SHOP_ID';
const String jsonKeyNearByShopModelDATATOTAL_DISTANCE = 'TOTAL_DISTANCE';
const String jsonKeyNearByShopModelDATASHOP_NAME = 'SHOP_NAME';
const String jsonKeyNearByShopModelDATAADDRESS = 'ADDRESS';
const String jsonKeyNearByShopModelDATASHOP_IMAGE = 'SHOP_IMAGE';
const String jsonKeyNearByShopModelDATASTATE_NAME = 'STATE_NAME';
const String jsonKeyNearByShopModelDATACITY_NAME = 'CITY_NAME';
const String jsonKeyNearByShopModelDATATALUKA_NAME = 'TALUKA_NAME';
const String jsonKeyNearByShopModelDATALATITUDE = 'LATITUDE';
const String jsonKeyNearByShopModelDATALONGITUDE = 'LONGITUDE';
const String jsonKeyNearByShopModelDATADEALER_NAME = 'DEALER_NAME';
const String jsonKeyNearByShopModelDATAVILLAGE = 'VILLAGE';
const String jsonKeyNearByShopModelDATAPESTISIDE_LIC_NO = 'PESTISIDE_LIC_NO';
const String jsonKeyNearByShopModelDATAFETLIZER_LIC_NO = 'FETLIZER_LIC_NO';
const String jsonKeyNearByShopModelDATASEED_LIC_NO = 'SEED_LIC_NO';
const String jsonKeyNearByShopModelDATACONTACT_NUMBER = 'CONTACT_NUMBER';
const String jsonKeyNearByShopModelDATASHOP_OWNER_PHOTO = 'SHOP_OWNER_PHOTO';
class NearByShopModelDATA {
/*
{
  "Row": 1,
  "SHOP_ID": 107,
  "TOTAL_DISTANCE": 0.00171560573,
  "SHOP_NAME": "bcdnx",
  "ADDRESS": "vwbwxwdhqz",
  "SHOP_IMAGE": "",
  "STATE_NAME": "MAHARASHTRA",
  "CITY_NAME": "Gurdaspur",
  "TALUKA_NAME": "Leh",
  "LATITUDE": "20.0086648",
  "LONGITUDE": "73.7638967",
  "DEALER_NAME": "vwbw",
  "VILLAGE": "wrqd",
  "PESTISIDE_LIC_NO": "p58575757f",
  "FETLIZER_LIC_NO": "ffh57577575",
  "SEED_LIC_NO": "8586585",
  "CONTACT_NUMBER": "9868585888",
  "SHOP_OWNER_PHOTO": ""
} 
*/

  int? Row;
  int? SHOP_ID;
  double? TOTAL_DISTANCE;
  String? SHOP_NAME;
  String? ADDRESS;
  String? SHOP_IMAGE;
  String? STATE_NAME;
  String? CITY_NAME;
  String? TALUKA_NAME;
  String? LATITUDE;
  String? LONGITUDE;
  String? DEALER_NAME;
  String? VILLAGE;
  String? PESTISIDE_LIC_NO;
  String? FETLIZER_LIC_NO;
  String? SEED_LIC_NO;
  String? CONTACT_NUMBER;
  String? SHOP_OWNER_PHOTO;

  NearByShopModelDATA({
    this.Row,
    this.SHOP_ID,
    this.TOTAL_DISTANCE,
    this.SHOP_NAME,
    this.ADDRESS,
    this.SHOP_IMAGE,
    this.STATE_NAME,
    this.CITY_NAME,
    this.TALUKA_NAME,
    this.LATITUDE,
    this.LONGITUDE,
    this.DEALER_NAME,
    this.VILLAGE,
    this.PESTISIDE_LIC_NO,
    this.FETLIZER_LIC_NO,
    this.SEED_LIC_NO,
    this.CONTACT_NUMBER,
    this.SHOP_OWNER_PHOTO,
  });
  NearByShopModelDATA.fromJson(Map<String, dynamic> json) {
    Row = json[jsonKeyNearByShopModelDATARow]?.toInt();
    SHOP_ID = json[jsonKeyNearByShopModelDATASHOP_ID]?.toInt();
    TOTAL_DISTANCE = json[jsonKeyNearByShopModelDATATOTAL_DISTANCE]?.toDouble();
    SHOP_NAME = json[jsonKeyNearByShopModelDATASHOP_NAME]?.toString();
    ADDRESS = json[jsonKeyNearByShopModelDATAADDRESS]?.toString();
    SHOP_IMAGE = json[jsonKeyNearByShopModelDATASHOP_IMAGE]?.toString();
    STATE_NAME = json[jsonKeyNearByShopModelDATASTATE_NAME]?.toString();
    CITY_NAME = json[jsonKeyNearByShopModelDATACITY_NAME]?.toString();
    TALUKA_NAME = json[jsonKeyNearByShopModelDATATALUKA_NAME]?.toString();
    LATITUDE = json[jsonKeyNearByShopModelDATALATITUDE]?.toString();
    LONGITUDE = json[jsonKeyNearByShopModelDATALONGITUDE]?.toString();
    DEALER_NAME = json[jsonKeyNearByShopModelDATADEALER_NAME]?.toString();
    VILLAGE = json[jsonKeyNearByShopModelDATAVILLAGE]?.toString();
    PESTISIDE_LIC_NO = json[jsonKeyNearByShopModelDATAPESTISIDE_LIC_NO]?.toString();
    FETLIZER_LIC_NO = json[jsonKeyNearByShopModelDATAFETLIZER_LIC_NO]?.toString();
    SEED_LIC_NO = json[jsonKeyNearByShopModelDATASEED_LIC_NO]?.toString();
    CONTACT_NUMBER = json[jsonKeyNearByShopModelDATACONTACT_NUMBER]?.toString();
    SHOP_OWNER_PHOTO = json[jsonKeyNearByShopModelDATASHOP_OWNER_PHOTO]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[jsonKeyNearByShopModelDATARow] = Row;
    data[jsonKeyNearByShopModelDATASHOP_ID] = SHOP_ID;
    data[jsonKeyNearByShopModelDATATOTAL_DISTANCE] = TOTAL_DISTANCE;
    data[jsonKeyNearByShopModelDATASHOP_NAME] = SHOP_NAME;
    data[jsonKeyNearByShopModelDATAADDRESS] = ADDRESS;
    data[jsonKeyNearByShopModelDATASHOP_IMAGE] = SHOP_IMAGE;
    data[jsonKeyNearByShopModelDATASTATE_NAME] = STATE_NAME;
    data[jsonKeyNearByShopModelDATACITY_NAME] = CITY_NAME;
    data[jsonKeyNearByShopModelDATATALUKA_NAME] = TALUKA_NAME;
    data[jsonKeyNearByShopModelDATALATITUDE] = LATITUDE;
    data[jsonKeyNearByShopModelDATALONGITUDE] = LONGITUDE;
    data[jsonKeyNearByShopModelDATADEALER_NAME] = DEALER_NAME;
    data[jsonKeyNearByShopModelDATAVILLAGE] = VILLAGE;
    data[jsonKeyNearByShopModelDATAPESTISIDE_LIC_NO] = PESTISIDE_LIC_NO;
    data[jsonKeyNearByShopModelDATAFETLIZER_LIC_NO] = FETLIZER_LIC_NO;
    data[jsonKeyNearByShopModelDATASEED_LIC_NO] = SEED_LIC_NO;
    data[jsonKeyNearByShopModelDATACONTACT_NUMBER] = CONTACT_NUMBER;
    data[jsonKeyNearByShopModelDATASHOP_OWNER_PHOTO] = SHOP_OWNER_PHOTO;
    return data;
  }
}

class NearByShopModel {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "Shop List",
  "Otp": null,
  "Static_Otp": null,
  "DATA": [
    {
      "Row": 1,
      "SHOP_ID": 107,
      "TOTAL_DISTANCE": 0.00171560573,
      "SHOP_NAME": "bcdnx",
      "ADDRESS": "vwbwxwdhqz",
      "SHOP_IMAGE": "",
      "STATE_NAME": "MAHARASHTRA",
      "CITY_NAME": "Gurdaspur",
      "TALUKA_NAME": "Leh",
      "LATITUDE": "20.0086648",
      "LONGITUDE": "73.7638967",
      "DEALER_NAME": "vwbw",
      "VILLAGE": "wrqd",
      "PESTISIDE_LIC_NO": "p58575757f",
      "FETLIZER_LIC_NO": "ffh57577575",
      "SEED_LIC_NO": "8586585",
      "CONTACT_NUMBER": "9868585888",
      "SHOP_OWNER_PHOTO": ""
    }
  ],
  "DATA1": [
    {
      "Column1": 1
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? Otp;
  String? Static_Otp;
  List<NearByShopModelDATA?>? DATA;
  List<NearByShopModelDATA1?>? DATA1;

  NearByShopModel({
    this.ResponseCode,
    this.ResponseMessage,
    this.Otp,
    this.Static_Otp,
    this.DATA,
    this.DATA1,
  });
  NearByShopModel.fromJson(Map<String, dynamic> json) {
    ResponseCode = json[jsonKeyNearByShopModelResponseCode]?.toString();
    ResponseMessage = json[jsonKeyNearByShopModelResponseMessage]?.toString();
    Otp = json[jsonKeyNearByShopModelOtp]?.toString();
    Static_Otp = json[jsonKeyNearByShopModelStatic_Otp]?.toString();
  if (json[jsonKeyNearByShopModelDATA] != null) {
  final v = json[jsonKeyNearByShopModelDATA];
  final arr0 = <NearByShopModelDATA>[];
  v.forEach((v) {
  arr0.add(NearByShopModelDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json[jsonKeyNearByShopModelDATA1] != null) {
  final v = json[jsonKeyNearByShopModelDATA1];
  final arr0 = <NearByShopModelDATA1>[];
  v.forEach((v) {
  arr0.add(NearByShopModelDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[jsonKeyNearByShopModelResponseCode] = ResponseCode;
    data[jsonKeyNearByShopModelResponseMessage] = ResponseMessage;
    data[jsonKeyNearByShopModelOtp] = Otp;
    data[jsonKeyNearByShopModelStatic_Otp] = Static_Otp;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data[jsonKeyNearByShopModelDATA] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data[jsonKeyNearByShopModelDATA1] = arr0;
    }
    return data;
  }
}
