///
/// Code generated by Sita Web Tool https://sita.app/json-to-dart/
///
class QuizeModelLIstModeDATA1 {
/*
{
  "FO_ID": 1209,
  "ANSWER_ID": 4730,
  "FARMER_ANSWER": null
} 
*/

  String? FO_ID;
  String? ANSWER_ID;
  String? FARMER_ANSWER;

  QuizeModelLIstModeDATA1({
    this.FO_ID,
    this.ANSWER_ID,
    this.FARMER_ANSWER,
  });
  QuizeModelLIstModeDATA1.fromJson(Map<String, dynamic> json) {
    FO_ID = json['FO_ID']?.toString();
    ANSWER_ID = json['ANSWER_ID']?.toString();
    FARMER_ANSWER = json['FARMER_ANSWER']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['FO_ID'] = FO_ID;
    data['ANSWER_ID'] = ANSWER_ID;
    data['FARMER_ANSWER'] = FARMER_ANSWER;
    return data;
  }
}

class QuizeModelLIstModeDATAQuestionOptionList {
/*
{
  "FOO_ID": "4727",
  "F_OPTION": "गहू",
  "IS_ANSWER": "No",
  "ANSWER_ID": "4730"
} 
*/

  String? FOO_ID;
  String? F_OPTION;
  String? IS_ANSWER;
  String? ANSWER_ID;

  QuizeModelLIstModeDATAQuestionOptionList({
    this.FOO_ID,
    this.F_OPTION,
    this.IS_ANSWER,
    this.ANSWER_ID,
  });
  QuizeModelLIstModeDATAQuestionOptionList.fromJson(Map<String, dynamic> json) {
    FOO_ID = json['FOO_ID']?.toString();
    F_OPTION = json['F_OPTION']?.toString();
    IS_ANSWER = json['IS_ANSWER']?.toString();
    ANSWER_ID = json['ANSWER_ID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['FOO_ID'] = FOO_ID;
    data['F_OPTION'] = F_OPTION;
    data['IS_ANSWER'] = IS_ANSWER;
    data['ANSWER_ID'] = ANSWER_ID;
    return data;
  }
}

class QuizeModelLIstModeDATA {
/*
{
  "FO_ID": "1209",
  "FARMER_RANK": null,
  "QC_ID": null,
  "QC_NAME": null,
  "QC_DATE": null,
  "FARMER_POINT": null,
  "FARMER_ANS": null,
  "ANS_TIME": null,
  "QUESTION": "खालीलपैकी कोणत्या पिकास नत्राची गरज सर्वात जास्त असते?",
  "ANSWER_ID": "4730",
  "CORRECT_ANS_COUNT": null,
  "TOTAL_POINT": null,
  "IS_COMPLETED": "No",
  "QuestionOptionList": [
    {
      "FOO_ID": "4727",
      "F_OPTION": "गहू",
      "IS_ANSWER": "No",
      "ANSWER_ID": "4730"
    }
  ]
} 
*/

  String? FO_ID;
  String? FARMER_RANK;
  String? QC_ID;
  String? QC_NAME;
  String? QC_DATE;
  String? FARMER_POINT;
  String? FARMER_ANS;
  String? ANS_TIME;
  String? QUESTION;
  String? ANSWER_ID;
  String? CORRECT_ANS_COUNT;
  String? TOTAL_POINT;
  String? IS_COMPLETED;
  List<QuizeModelLIstModeDATAQuestionOptionList?>? QuestionOptionList;

  QuizeModelLIstModeDATA({
    this.FO_ID,
    this.FARMER_RANK,
    this.QC_ID,
    this.QC_NAME,
    this.QC_DATE,
    this.FARMER_POINT,
    this.FARMER_ANS,
    this.ANS_TIME,
    this.QUESTION,
    this.ANSWER_ID,
    this.CORRECT_ANS_COUNT,
    this.TOTAL_POINT,
    this.IS_COMPLETED,
    this.QuestionOptionList,
  });
  QuizeModelLIstModeDATA.fromJson(Map<String, dynamic> json) {
    FO_ID = json['FO_ID']?.toString();
    FARMER_RANK = json['FARMER_RANK']?.toString();
    QC_ID = json['QC_ID']?.toString();
    QC_NAME = json['QC_NAME']?.toString();
    QC_DATE = json['QC_DATE']?.toString();
    FARMER_POINT = json['FARMER_POINT']?.toString();
    FARMER_ANS = json['FARMER_ANS']?.toString();
    ANS_TIME = json['ANS_TIME']?.toString();
    QUESTION = json['QUESTION']?.toString();
    ANSWER_ID = json['ANSWER_ID']?.toString();
    CORRECT_ANS_COUNT = json['CORRECT_ANS_COUNT']?.toString();
    TOTAL_POINT = json['TOTAL_POINT']?.toString();
    IS_COMPLETED = json['IS_COMPLETED']?.toString();
  if (json['QuestionOptionList'] != null) {
  final v = json['QuestionOptionList'];
  final arr0 = <QuizeModelLIstModeDATAQuestionOptionList>[];
  v.forEach((v) {
  arr0.add(QuizeModelLIstModeDATAQuestionOptionList.fromJson(v));
  });
    QuestionOptionList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['FO_ID'] = FO_ID;
    data['FARMER_RANK'] = FARMER_RANK;
    data['QC_ID'] = QC_ID;
    data['QC_NAME'] = QC_NAME;
    data['QC_DATE'] = QC_DATE;
    data['FARMER_POINT'] = FARMER_POINT;
    data['FARMER_ANS'] = FARMER_ANS;
    data['ANS_TIME'] = ANS_TIME;
    data['QUESTION'] = QUESTION;
    data['ANSWER_ID'] = ANSWER_ID;
    data['CORRECT_ANS_COUNT'] = CORRECT_ANS_COUNT;
    data['TOTAL_POINT'] = TOTAL_POINT;
    data['IS_COMPLETED'] = IS_COMPLETED;
    if (QuestionOptionList != null) {
      final v = QuestionOptionList;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['QuestionOptionList'] = arr0;
    }
    return data;
  }
}

class QuizeModelLIstMode {
/*
{
  "ResponseCode": "0",
  "ResponseMessage": "My Quiz List",
  "ID": null,
  "URL1": null,
  "URL2": null,
  "DATA": [
    {
      "FO_ID": "1209",
      "FARMER_RANK": null,
      "QC_ID": null,
      "QC_NAME": null,
      "QC_DATE": null,
      "FARMER_POINT": null,
      "FARMER_ANS": null,
      "ANS_TIME": null,
      "QUESTION": "खालीलपैकी कोणत्या पिकास नत्राची गरज सर्वात जास्त असते?",
      "ANSWER_ID": "4730",
      "CORRECT_ANS_COUNT": null,
      "TOTAL_POINT": null,
      "IS_COMPLETED": "No",
      "QuestionOptionList": [
        {
          "FOO_ID": "4727",
          "F_OPTION": "गहू",
          "IS_ANSWER": "No",
          "ANSWER_ID": "4730"
        }
      ]
    }
  ],
  "DATA1": [
    {
      "FO_ID": 1209,
      "ANSWER_ID": 4730,
      "FARMER_ANSWER": null
    }
  ]
} 
*/

  String? ResponseCode;
  String? ResponseMessage;
  String? ID;
  String? URL1;
  String? URL2;
  List<QuizeModelLIstModeDATA?>? DATA;
  List<QuizeModelLIstModeDATA1?>? DATA1;

  QuizeModelLIstMode({
    this.ResponseCode,
    this.ResponseMessage,
    this.ID,
    this.URL1,
    this.URL2,
    this.DATA,
    this.DATA1,
  });
  QuizeModelLIstMode.fromJson(Map<String, dynamic> json) {
    ResponseCode = json['ResponseCode']?.toString();
    ResponseMessage = json['ResponseMessage']?.toString();
    ID = json['ID']?.toString();
    URL1 = json['URL1']?.toString();
    URL2 = json['URL2']?.toString();
  if (json['DATA'] != null) {
  final v = json['DATA'];
  final arr0 = <QuizeModelLIstModeDATA>[];
  v.forEach((v) {
  arr0.add(QuizeModelLIstModeDATA.fromJson(v));
  });
    DATA = arr0;
    }
  if (json['DATA1'] != null) {
  final v = json['DATA1'];
  final arr0 = <QuizeModelLIstModeDATA1>[];
  v.forEach((v) {
  arr0.add(QuizeModelLIstModeDATA1.fromJson(v));
  });
    DATA1 = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResponseCode'] = ResponseCode;
    data['ResponseMessage'] = ResponseMessage;
    data['ID'] = ID;
    data['URL1'] = URL1;
    data['URL2'] = URL2;
    if (DATA != null) {
      final v = DATA;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA'] = arr0;
    }
    if (DATA1 != null) {
      final v = DATA1;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['DATA1'] = arr0;
    }
    return data;
  }
}
